version: 2.1
jobs:
  compile:
   docker:
      - image: tyuzu/kernel:build
   steps:
      - run:
          TG_TOKEN:
             from_secret: TG_TOKEN
          TG_CHAT_ID:
             from_secret: TG_CHAT_ID
          GH_USERNAME:
             from_secret: GH_USERNAME
          GH_EMAIL:
             from_secret: GH_EMAIL
          GH_TOKEN:
             from_secret: GH_TOKEN
          GH_PUSH_REPO_URL:
             from_secret: GH_PUSH_REPO_URL
          command: |
           git clone --depth=1 https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} -b ${CIRCLE_BRANCH} .
           bash .circleci/build.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
