version: 2.1
jobs:
  compile:
   docker:
      - image: tyuzu/kernel:build
   steps:
      - run:
          TG_TOKEN:
             from_secret: TG_TOKEN
          TG_CHAT_ID:
             from_secret: TG_CHAT_ID
          command: |
           git clone --depth=1 https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} -b ${CIRCLE_BRANCH} .
           bash .circleci/build.sh --proton
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
