version: 2.2

jobs:
  clang:
   docker:
      - image: tyuzu/kernel:build
   steps:
      - run:
          command: |
           git clone --depth=1 https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} -b ${CIRCLE_BRANCH} .
           bash .circleci/build.sh --proton
             
   gcc:
    docker:
      - image: tyuzu/kernel:build
    steps:
      - run:
          command: |
           git clone --depth=1 https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} -b ${CIRCLE_BRANCH} .
           bash .circleci/build.sh --gcc

workflows:
  version: 2.2
  cooking:
    jobs:
      - clang
      - gcc
