version: 2.1

jobs:
  compile:
   docker:
      - image: tyuzu/kernel:build
   steps:
      - run: git clone --depth=1 https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} -b ${CIRCLE_BRANCH} .
      - run: bash .circleci/build --azure #--azure, --aosp
             
workflows:
  version: 2.1
  build:
    jobs:
      - compile
